export const retiredBlogRedirects = [
  // Buyer and service articles consolidate into hiring and outsourcing intent.
  { source: "/blog/video-editing-agency-how-to-hire-one-without-losing-creative-control", destination: "/blog/how-to-hire-video-editors" },
  { source: "/blog/video-editing-services-that-actually-fit-agency-deadlines", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/hire-a-video-editor-or-use-an-editing-agency-the-clear-buyer-guide", destination: "/blog/how-to-hire-video-editors" },
  { source: "/blog/outsourced-video-editing-cost-workflow-and-quality-checklist", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/youtube-video-editing-agency-guide-for-channels-that-need-consistency", destination: "/blog/how-to-find-youtubers-who-need-video-editors" },
  { source: "/blog/long-form-video-editing-services-for-podcasts-courses-and-youtube", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/ugc-video-editing-services-hooks-captions-cuts-and-ad-variants", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/real-estate-video-editing-services-for-listings-reels-and-agent-brands", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/wedding-video-editing-outsourcing-what-studios-should-check-first", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/corporate-video-editing-services-for-teams-with-brand-guidelines", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/podcast-video-editing-services-clips-full-episodes-and-show-notes", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/ecommerce-video-editing-services-for-product-ads-and-social-proof", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/video-editing-retainer-vs-per-project-editing-which-is-better", destination: "/blog/how-much-should-i-charge-for-video-editing" },
  { source: "/blog/video-editing-pricing-what-agencies-and-creators-should-budget", destination: "/blog/how-much-should-i-charge-for-video-editing" },
  { source: "/blog/best-video-editing-company-what-to-look-for-before-you-pay", destination: "/blog/how-to-hire-video-editors" },
  { source: "/blog/video-editor-for-social-media-agency-checklist-for-daily-content", destination: "/blog/how-to-hire-video-editors" },
  { source: "/blog/post-production-services-editing-sound-color-captions-and-delivery", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/remote-video-editing-team-how-agencies-can-run-delivery-smoothly", destination: "/blog/how-to-scale-a-video-editing-business" },

  // Freelancer career articles consolidate into client-acquisition and pricing intent.
  { source: "/blog/how-freelancers-can-join-a-video-editing-agency-and-get-better-projects", destination: "/blog/how-to-get-video-editing-clients-without-upwork" },
  { source: "/blog/video-editing-agency-jobs-skills-portfolio-and-application-tips", destination: "/blog/how-to-get-video-editing-clients-as-a-beginner" },
  { source: "/blog/freelance-video-editor-portfolio-what-agencies-actually-want-to-see", destination: "/blog/how-to-get-video-editing-clients-as-a-beginner" },
  { source: "/blog/video-editor-application-guide-how-to-stand-out-without-overselling", destination: "/blog/how-to-get-your-first-video-editing-client" },
  { source: "/blog/freelance-video-editing-rates-how-to-price-agency-work", destination: "/blog/how-much-should-i-charge-for-video-editing" },
  { source: "/blog/video-editor-skills-agencies-look-for-before-assigning-paid-work", destination: "/blog/how-to-get-video-editing-clients-as-a-beginner" },
  { source: "/blog/remote-video-editing-jobs-where-agency-editors-can-build-consistent-work", destination: "/blog/how-to-get-video-editing-clients-without-upwork" },
  { source: "/blog/video-editor-profile-checklist-for-getting-hired-by-agencies", destination: "/blog/how-to-get-video-editing-clients-as-a-beginner" },
  { source: "/blog/video-editing-test-project-how-freelancers-should-approach-it", destination: "/blog/how-to-get-your-first-video-editing-client" },
  { source: "/blog/agency-video-editor-workflow-how-freelancers-can-deliver-like-a-pro", destination: "/blog/how-to-manage-video-editing-clients" },
  { source: "/blog/short-form-video-editor-jobs-portfolio-examples-and-skills-to-show", destination: "/blog/how-to-get-video-editing-clients-as-a-beginner" },
  { source: "/blog/youtube-editor-jobs-how-freelancers-can-win-long-term-channel-work", destination: "/blog/how-to-find-youtubers-who-need-video-editors" },
  { source: "/blog/video-editor-onboarding-what-freelancers-should-prepare-before-joining", destination: "/blog/how-to-manage-video-editing-clients" },
  { source: "/blog/freelance-editor-contract-basics-for-agency-projects", destination: "/blog/video-editing-proposal-template" },
  { source: "/blog/video-editing-revision-process-a-freelancer-guide-to-happier-clients", destination: "/blog/how-to-manage-video-editing-clients" },
  { source: "/blog/caption-editing-portfolio-how-to-show-short-form-skill-fast", destination: "/blog/how-to-get-video-editing-clients-as-a-beginner" },
  { source: "/blog/color-correction-portfolio-tips-for-freelance-video-editors", destination: "/blog/how-to-get-video-editing-clients-as-a-beginner" },
  { source: "/blog/motion-graphics-editor-jobs-how-to-package-your-reel-for-agencies", destination: "/blog/how-to-get-video-editing-clients-as-a-beginner" },
  { source: "/blog/freelance-post-production-work-how-editors-can-join-agency-pipelines", destination: "/blog/how-to-get-video-editing-clients-without-upwork" },

  // Workflow articles consolidate into client operations and agency growth.
  { source: "/blog/post-production-workflow-a-practical-system-for-agencies-and-creators", destination: "/blog/how-to-manage-video-editing-clients" },
  { source: "/blog/post-production-agency-vs-freelance-editor-which-should-you-choose", destination: "/blog/how-to-hire-video-editors" },
  { source: "/blog/video-post-production-checklist-before-you-send-footage-to-editors", destination: "/blog/how-to-outsource-video-editing" },
  { source: "/blog/editing-workflow-for-agencies-intake-assignment-review-and-delivery", destination: "/blog/how-to-manage-video-editing-clients" },
  { source: "/blog/video-revision-workflow-how-to-avoid-endless-feedback-loops", destination: "/blog/how-to-manage-video-editing-clients" },
  { source: "/blog/content-repurposing-workflow-turn-one-shoot-into-weeks-of-assets", destination: "/blog/how-to-scale-a-video-editing-business" },
  { source: "/blog/video-delivery-process-how-agencies-can-ship-faster-with-fewer-errors", destination: "/blog/how-to-manage-video-editing-clients" },
  { source: "/blog/remote-post-production-how-to-manage-editors-files-and-feedback", destination: "/blog/how-to-manage-video-editing-clients" },
  { source: "/blog/video-editing-quality-control-checks-before-client-delivery", destination: "/blog/how-to-manage-video-editing-clients" },
  { source: "/blog/video-editing-brief-template-what-to-include-before-assigning-work", destination: "/blog/video-editing-proposal-template" },
  { source: "/blog/youtube-post-production-workflow-for-full-episodes-and-shorts", destination: "/blog/how-to-find-youtubers-who-need-video-editors" },
  { source: "/blog/social-media-post-production-how-to-build-a-clip-engine", destination: "/blog/how-to-scale-a-video-editing-business" },
  { source: "/blog/agency-production-system-build-a-repeatable-editing-operation", destination: "/blog/how-to-scale-a-video-editing-business" },
  { source: "/blog/video-asset-management-for-agencies-with-multiple-editors", destination: "/blog/how-to-scale-a-video-editing-business" },
  { source: "/blog/editing-project-management-how-to-keep-clients-editors-and-managers-aligned", destination: "/blog/how-to-manage-video-editing-clients" },
  { source: "/blog/post-production-cost-what-drives-editing-sound-color-and-motion-pricing", destination: "/blog/how-much-should-i-charge-for-video-editing" },
  { source: "/blog/video-editing-sop-standard-operating-procedure-for-agency-delivery", destination: "/blog/how-to-scale-a-video-editing-business" },
  { source: "/blog/post-production-manager-role-responsibilities-and-when-to-hire-one", destination: "/blog/how-to-scale-a-video-editing-business" },
  { source: "/blog/ankit-rathore-and-the-video-editing-industry-lessons-for-agency-growth", destination: "/blog/how-to-scale-a-video-editing-business" },
] as const;
