import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
function load(file,mocks={}){const source=readFileSync(new URL('../'+file,import.meta.url),'utf8');const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const box={exports:{}};new Function('module','exports','require',code)(box,box.exports,id=>{if(id in mocks)return mocks[id];throw new Error('Unexpected import '+id);});return box.exports;}
const validation=load('src/lib/connected-platform/learning-validation.ts');
const input={userId:'qa-user',audience:'AGENCY',courseId:'qa-course',chapterId:'qa-chapter',lessonId:'qa-lesson',playbackSessionId:'qa-session',eventId:'qa-event',activeSeconds:10,playbackState:'PLAYING',watchedSeconds:0,durationSeconds:100,positionSeconds:10};
function harness(){
 const state={progress:null,session:null,events:new Map(),lockCount:0,user:{packageId:'free',packageStatus:'ACTIVE',packageExpiresAt:null},lesson:{id:'qa-lesson',estimatedDuration:100,completionThreshold:90,module:{id:'qa-chapter',isPublished:true,accessMode:'ALL_MATCHING_PACKAGES',packageAccess:[]}}};
 const tx={
  $queryRaw:async()=>{state.lockCount++;return [];},
  learningWatchEvent:{findUnique:async({where})=>state.events.get(where.id)||null,create:async({data})=>{state.events.set(data.id,data);return data;}},
  salesTrainingProgress:{findUnique:async()=>state.progress,upsert:async({create,update})=>{state.progress=state.progress?{...state.progress,...Object.fromEntries(Object.entries(update).filter(([,v])=>v!==undefined))}:create;return state.progress;}},
  learningWatchSession:{findUnique:async()=>state.session,upsert:async({create,update})=>{state.session=state.session?{...state.session,...update,activeWatchedSeconds:state.session.activeWatchedSeconds+update.activeWatchedSeconds.increment}:create;return state.session;},aggregate:async()=>({_sum:{activeWatchedSeconds:state.session?.activeWatchedSeconds??0},_max:{durationSeconds:state.session?.durationSeconds??0}}),update:async()=>state.session},
 };
 const prisma={...tx,salesTrainingLesson:{findFirst:async()=>state.lesson},appAuthUser:{findUnique:async()=>state.user},$transaction:async fn=>fn(tx),salesTrainingModule:{findMany:async()=>[{id:'one',courseId:'a'},{id:'two',courseId:'b'}]}};
 const service=load('src/lib/connected-platform/lms.ts',{'server-only':{},'node:crypto':{randomUUID:()=> 'random-qa'},'@prisma/client':{Prisma:{sql:()=>({}),PrismaClientKnownRequestError:class extends Error{}}},'@/lib/connected-platform/youtube':{},'@/lib/prisma':{prisma},'./learning-validation':validation});
 return {state,service};
}
test('invalid watch payloads fail before database mutation',()=>{for(const patch of [{durationSeconds:NaN},{durationSeconds:0},{positionSeconds:1000},{activeSeconds:20},{activeSeconds:Infinity}])assert.throws(()=>validation.validateWatchInput({...input,...patch}),validation.LearningInputError);});
test('reorder rejects duplicate IDs, duplicate order and invalid values',()=>{for(const items of [[],[{id:'a',sortOrder:0},{id:'a',sortOrder:1}],[{id:'a',sortOrder:0},{id:'b',sortOrder:0}],[{id:'a',sortOrder:-1}]])assert.throws(()=>validation.validateLearningReorder(items));assert.doesNotThrow(()=>validation.validateLearningReorder([{id:'a',sortOrder:0},{id:'b',sortOrder:1}]));});
test('same playback event is acknowledged twice but counted once',async()=>{const {state,service}=harness();const first=await service.updateConnectedLmsProgress(input);const again=await service.updateConnectedLmsProgress(input);assert.equal(first.watchedSeconds,10);assert.equal(again.watchedSeconds,10);assert.equal(state.events.size,1);assert.equal(state.lockCount,2);});
test('event IDs cannot be reused across learners or sessions',async()=>{const {state,service}=harness();state.events.set(input.eventId,{userId:'other',lessonId:input.lessonId,sessionId:input.playbackSessionId});await assert.rejects(service.updateConnectedLmsProgress(input),e=>e.status===409);assert.equal(state.progress,null);});
test('expired package cannot save progress on a selected-package chapter',async()=>{const {state,service}=harness();state.lesson.module.accessMode='SELECTED_PACKAGES';state.lesson.module.packageAccess=[{packageId:'free'}];state.user.packageExpiresAt=new Date('2020-01-01');await assert.rejects(service.updateConnectedLmsProgress(input),e=>e.status===402);assert.equal(state.events.size,0);});
test('unpublished chapters reject lesson progress',async()=>{const {state,service}=harness();state.lesson.module.isPublished=false;await assert.rejects(service.updateConnectedLmsProgress(input),e=>e.status===404);assert.equal(state.events.size,0);});
test('previously completed lessons never regress on another viewing',async()=>{const {state,service}=harness();state.progress={status:'COMPLETED',progressPercent:100,watchedSeconds:100,completedAt:new Date(),confirmedAt:new Date()};const result=await service.updateConnectedLmsProgress(input);assert.equal(result.status,'COMPLETED');assert.equal(result.progressPercent,100);});
test('admin cannot reorder chapters across different playlists',async()=>{const {service}=harness();await assert.rejects(service.reorderConnectedLmsEntities({entity:'chapter',items:[{id:'one',sortOrder:0},{id:'two',sortOrder:1}]}),/same playlist/);});
test('mobile routes return typed JSON errors without leaking database exceptions',()=>{for(const route of ['src/app/api/mobile/v2/lms/route.ts','src/app/api/mobile/v2/lms/progress/route.ts']){const source=readFileSync(new URL('../'+route,import.meta.url),'utf8');assert.match(source,/status: 503/);assert.doesNotMatch(source,/error instanceof Error \? error.message/);}});
test('admin editing preserves IDs and provides sibling order controls',()=>{const editor=readFileSync(new URL('../src/components/super-admin/learning-content-editor.tsx',import.meta.url),'utf8');const page=readFileSync(new URL('../src/components/super-admin/connected-platform-control.tsx',import.meta.url),'utf8');assert.match(editor,/id: content.id/);assert.match(editor,/packageIds: form.getAll/);assert.match(page,/Edit chapter & access/);assert.match(page,/moveLearning\("lesson", chapter.lessons/);assert.match(page,/formElement.reset/);});
