-- Keep legacy agency packages for existing subscriptions, but remove them from
-- new registration choices. New agencies choose one of two plans below.
UPDATE "packages"
SET "isVisibleOnRegistration" = false,
    "allowRegistration" = false,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "id" IN ('pkg-agency-launch', 'pkg-agency-scale');

INSERT INTO "packages" (
  "id", "name", "slug", "packageType", "shortSubtitle", "description",
  "badgeText", "ctaLabel", "billingType", "billingInterval", "currency",
  "amount", "priceMonthly", "priceYearly", "isFree", "isActive",
  "isVisibleOnRegistration", "isRecommended", "allowRegistration",
  "paymentRequired", "autoRenewEnabled", "durationDays", "sortOrder",
  "selectedSummaryBullets", "compareHighlights", "featureOrder",
  "activeProjectLimit", "teamMemberLimit", "editorFreelancerLimit",
  "chatAccess", "clientChat", "teamChat", "whatsappIntegration",
  "aiToolsAccess", "prioritySupport", "analyticsAccess", "advancedAnalytics",
  "invoiceTools", "paymentCollectionTools", "brandingCustomization",
  "automationTools", "apiAccess", "webhookAccess", "dedicatedManager",
  "upgradePathIds", "downgradePathIds", "isDefaultFreePackage",
  "createdAt", "updatedAt"
)
VALUES
  (
    'pkg-agency-freemium', 'Agency Freemium', 'agency-freemium', 'AGENCY',
    'Start with two editors',
    'Core agency chat and team tools with assignment access for up to two confirmed editors.',
    'Free', 'Start free', 'FREE', 'CUSTOM', 'INR', 0, 0, 0,
    true, true, true, false, true, false, false, 3650, 3,
    ARRAY['WhatsApp and Instagram inbox', 'Invite and confirm freelancers', 'Assign chats to up to 2 editors'],
    ARRAY['Stable multichannel chat', 'Confirmed team members', '2 editor seats'],
    ARRAY[]::TEXT[], 5, 2, 2,
    true, true, true, true,
    false, false, false, false, false, false, false, false, false, false, false,
    ARRAY['pkg-agency-premium'], ARRAY[]::TEXT[], true,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
  ),
  (
    'pkg-agency-premium', 'Agency Premium', 'agency-premium', 'AGENCY',
    'Unlock every agency feature',
    'Unlimited editor assignments, full integrations, automation, analytics, and priority support.',
    'Premium', 'Subscribe to Premium', 'RECURRING', 'MONTHLY', 'INR', 2000, 2000, 17700,
    false, true, true, true, true, true, true, 30, 4,
    ARRAY['Unlimited editor assignments', 'All chat and integration features', 'Automation, analytics, and priority support'],
    ARRAY['Unlimited editors', 'All integrations', 'Full automation and analytics'],
    ARRAY[]::TEXT[], NULL, NULL, NULL,
    true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true,
    ARRAY[]::TEXT[], ARRAY['pkg-agency-freemium'], false,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
  )
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "slug" = EXCLUDED."slug",
  "shortSubtitle" = EXCLUDED."shortSubtitle",
  "description" = EXCLUDED."description",
  "badgeText" = EXCLUDED."badgeText",
  "ctaLabel" = EXCLUDED."ctaLabel",
  "billingType" = EXCLUDED."billingType",
  "billingInterval" = EXCLUDED."billingInterval",
  "amount" = EXCLUDED."amount",
  "priceMonthly" = EXCLUDED."priceMonthly",
  "priceYearly" = EXCLUDED."priceYearly",
  "isFree" = EXCLUDED."isFree",
  "isActive" = true,
  "isVisibleOnRegistration" = true,
  "isRecommended" = EXCLUDED."isRecommended",
  "allowRegistration" = true,
  "paymentRequired" = EXCLUDED."paymentRequired",
  "autoRenewEnabled" = EXCLUDED."autoRenewEnabled",
  "durationDays" = EXCLUDED."durationDays",
  "sortOrder" = EXCLUDED."sortOrder",
  "selectedSummaryBullets" = EXCLUDED."selectedSummaryBullets",
  "compareHighlights" = EXCLUDED."compareHighlights",
  "activeProjectLimit" = EXCLUDED."activeProjectLimit",
  "teamMemberLimit" = EXCLUDED."teamMemberLimit",
  "editorFreelancerLimit" = EXCLUDED."editorFreelancerLimit",
  "chatAccess" = EXCLUDED."chatAccess",
  "clientChat" = EXCLUDED."clientChat",
  "teamChat" = EXCLUDED."teamChat",
  "whatsappIntegration" = EXCLUDED."whatsappIntegration",
  "aiToolsAccess" = EXCLUDED."aiToolsAccess",
  "prioritySupport" = EXCLUDED."prioritySupport",
  "analyticsAccess" = EXCLUDED."analyticsAccess",
  "advancedAnalytics" = EXCLUDED."advancedAnalytics",
  "invoiceTools" = EXCLUDED."invoiceTools",
  "paymentCollectionTools" = EXCLUDED."paymentCollectionTools",
  "brandingCustomization" = EXCLUDED."brandingCustomization",
  "automationTools" = EXCLUDED."automationTools",
  "apiAccess" = EXCLUDED."apiAccess",
  "webhookAccess" = EXCLUDED."webhookAccess",
  "dedicatedManager" = EXCLUDED."dedicatedManager",
  "upgradePathIds" = EXCLUDED."upgradePathIds",
  "downgradePathIds" = EXCLUDED."downgradePathIds",
  "isDefaultFreePackage" = EXCLUDED."isDefaultFreePackage",
  "updatedAt" = CURRENT_TIMESTAMP;
